# mac setup
# 1. mkdir /tmp/vagrant_temp
# 2. export VAGRANT_HOME=/tmp/vagrant_temp

# 1. vagrant up
# 2. vagrant ssh
# 3. vagrant halt

Vagrant.configure("2") do |config|
    config.vm.box = "debian/jessie64"
end